# Generated by Django 4.0.4 on 2022-05-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILIARES', '0002_alter_familia_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familia',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
