# Generated by Django 4.0.4 on 2022-05-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILIARES', '0003_familia_shirt_size_alter_familia_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='familia',
            name='parentesco',
            field=models.CharField(choices=[('P', 'Padre'), ('M', 'Madre'), ('H', 'Hijo/a'), ('Pr', 'Primo/a'), ('T', 'Tio/a')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
