# Generated by Django 4.0.4 on 2022-05-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILIARES', '0004_remove_familia_shirt_size_familia_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='parentesco',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hijo/a', 'Hijo/a'), ('Primo/a', 'Primo/a'), ('Tio/a', 'Tio/a'), ('Suegro/a', 'Suegro/a')], max_length=8),
        ),
    ]
