# Generated by Django 4.0.4 on 2022-05-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILIARES', '0005_alter_familia_parentesco'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='e_civil',
            field=models.CharField(choices=[('Casado/a', 'Casado/a'), ('Soltero/a', 'Soltero/a'), ('Viudo/a', 'Viudo/a'), ('Divorciado/a', 'Divorciado/a')], default=3, max_length=12),
            preserve_default=False,
        ),
    ]
